### ISSUE TITLE
Open Graph y Twitter Cards

### ISSUE THREAD

**Issue by picandocodigo** [datauy/atuservicio_rails#15]
Tendríamos que tener una imagen para mostrar cuando la gente comparte los links del sitio en redes sociales.

Facebook y otros tantos siguen el protocolo [Open Graph](http://ogp.me/), en el que básicamente hay que agregar estos tags, pero nos falta una imagen (lo mismo para Twitter Cards):

```html
<meta property="og:title" content="Comparando - AtuServicio.uy" />
<meta property="og:description" content="Comparando Medica Uruguaya en AtuServicio.uy" />
<meta property="og:type" content="website" />
<meta property="og:url" content="http://localhost:3000/comparar?selected_providers=3567" />
<meta property="og:image" content="FALTA" />
```

@danielcarranza ¿Esto se lo pedimos a Agustín y Flavia o querés meterle mano? Se puede usar simplemente el logo de atuservicio con un color de fondo y listo, como quieras.

**Comment by danielcarranza** [comment]
![atsopengraph](https://cloud.githubusercontent.com/assets/1755382/12344036/e709d49e-bb17-11e5-9b6e-1a01d73c555d.png)

Vamos con lo simple ya, así no le agregamos cosas a Agustín y Flavia. Va a tamaño sugerido por Facebook. Tiro también una sugerencia para título y el texto, buscando además que no haya que personalizarlo para cada caso:

title: ATuServicio.uy - Comparación
description: Compará éstos prestadores de Salud para elegir informado o personalizalo para conocer a fondo los indicadores del tuyo.

Vamos a necesitar uno para el home...

title: ATuServicio.uy
description: Toda la información e indicadores de todos los prestadores de Salud de Uruguay para elegir informado o conocer a fondo los indicadores de tu servicio de salud.

Y también uno para Twitter...

Indicadores de prestadores de Salud para elegir informado o conocer a fondo: http://atuservicio.uy
Un proyecto de @DATAuy y @MSPUruguay

**Comment by picandocodigo** [comment]
Va quedando por acá: 4b5cac2e1cf45e1492668c0171badb8c68591090

**Comment by picandocodigo** [comment]
Cierro porque quedó pronto, cualquier cosa lo volvemos a abrir.
