### ISSUE TITLE
El botón "comparar ahora" no aparece en el cabezal, antes de quedar fijo al deslizar.

### ISSUE THREAD

**Issue by danielcarranza** [datauy/atuservicio_rails#18]
Me pregunto si no debería aparecer también al poner una sola, porque capaz que sólo quiero profundizar datos de la que me interesa. O mejor, enlazar el nombre del prestador a eso (creo otro issue).

**Comment by picandocodigo** [comment]
Quedó lo de enlazar a los datos de uno solo en el nombre del prestador. Ahora, esto en particular ¿capaz que también habría que agregarlo? Que al elegir uno ya aparezca el botón. Es cambiar una condición mínima, así que en el código no afecta casi nada.

**Comment by danielcarranza** [comment]
Si, si es fácil de cabeza.

**Comment by picandocodigo** [comment]
Listo, pusheando eso a staging...

**Comment by danielcarranza** [comment]
Hojaldre que "comparar ahora" todavía no aparece en el cabezal, antes de quedar fijo al deslizar :)

**Comment by picandocodigo** [comment]
Ah, encontraste un bug ahí. Ya lo corregí, no aparecía nunca en el header antes de deslizar.

**Comment by danielcarranza** [comment]
🐞
