### ISSUE TITLE
Tildes y espacios

### ISSUE THREAD

**Issue by danielcarranza** [datauy/atuservicio_rails#26]
En la frase junto a los dropdown del home está mal "...elegí cuál te corresponde y compará..." y también faltan tildes y hay underscores en lugar de espacios en todas las especialidades de las sedes.

@picandocodigo Si querés guíame a los archivos y corrijo yo.

**Comment by picandocodigo** [comment]
Quedó corregido acá: https://github.com/datauy/atuservicio_rails/commit/3e321de3546f3ebe346a15130ec289d9b09c7478
